/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalState } from './approvalState';


export interface ApprovalDecisionRequest { 
    decision: ApprovalDecisionRequest.DecisionEnum;
    reasonCode?: string | null;
    note?: string | null;
    expectedState?: ApprovalState;
}
export namespace ApprovalDecisionRequest {
    export type DecisionEnum = 'APPROVE' | 'REJECT' | 'REQUEST_CHANGES';
    export const DecisionEnum = {
        Approve: 'APPROVE' as DecisionEnum,
        Reject: 'REJECT' as DecisionEnum,
        RequestChanges: 'REQUEST_CHANGES' as DecisionEnum
    };
}


