/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalState } from './approvalState';
import { Decision } from './decision';


export interface ApprovalDetail { 
    approvalId: string;
    type: string;
    state: ApprovalState;
    entityType: string;
    entityId: string;
    /**
     * Domain payload snapshot for UI rendering
     */
    payload?: { [key: string]: any; };
    decisions?: Array<Decision>;
    createdAt: string;
}
export namespace ApprovalDetail {
}


