/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApprovalState } from './approvalState';


export interface ApprovalSummary { 
    approvalId: string;
    type: string;
    state: ApprovalState;
    priority?: ApprovalSummary.PriorityEnum | null;
    entityType: string;
    entityId: string;
    requester?: string | null;
    createdAt: string;
}
export namespace ApprovalSummary {
    export type PriorityEnum = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    export const PriorityEnum = {
        Low: 'LOW' as PriorityEnum,
        Medium: 'MEDIUM' as PriorityEnum,
        High: 'HIGH' as PriorityEnum,
        Urgent: 'URGENT' as PriorityEnum
    };
}


