/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ApprovalState = 'PENDING' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'CHANGES_REQUESTED' | 'CANCELED';

export const ApprovalState = {
    Pending: 'PENDING' as ApprovalState,
    InReview: 'IN_REVIEW' as ApprovalState,
    Approved: 'APPROVED' as ApprovalState,
    Rejected: 'REJECTED' as ApprovalState,
    ChangesRequested: 'CHANGES_REQUESTED' as ApprovalState,
    Canceled: 'CANCELED' as ApprovalState
};

