/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Assignment { 
    type: Assignment.TypeEnum;
    targetId: string;
    roleId?: string | null;
    effectiveFrom?: string | null;
    effectiveTo?: string | null;
}
export namespace Assignment {
    export type TypeEnum = 'COMMUNITY' | 'NUCLEUS' | 'STRUCTURE_POSITION';
    export const TypeEnum = {
        Community: 'COMMUNITY' as TypeEnum,
        Nucleus: 'NUCLEUS' as TypeEnum,
        StructurePosition: 'STRUCTURE_POSITION' as TypeEnum
    };
}


