/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ControlAlertItem { 
    alertId: string;
    severity: ControlAlertItem.SeverityEnum;
    state: ControlAlertItem.StateEnum;
    title: string;
    description?: string | null;
    createdAt: string;
}
export namespace ControlAlertItem {
    export type SeverityEnum = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    export const SeverityEnum = {
        Info: 'INFO' as SeverityEnum,
        Low: 'LOW' as SeverityEnum,
        Medium: 'MEDIUM' as SeverityEnum,
        High: 'HIGH' as SeverityEnum,
        Critical: 'CRITICAL' as SeverityEnum
    };
    export type StateEnum = 'OPEN' | 'ACKED' | 'RESOLVED';
    export const StateEnum = {
        Open: 'OPEN' as StateEnum,
        Acked: 'ACKED' as StateEnum,
        Resolved: 'RESOLVED' as StateEnum
    };
}


