/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceSelector } from './audienceSelector';


export interface CreateNotificationRequest { 
    title: string;
    channel: CreateNotificationRequest.ChannelEnum;
    audience: AudienceSelector;
    templateId?: string | null;
    variables?: { [key: string]: any; } | null;
    scheduleAt?: string | null;
}
export namespace CreateNotificationRequest {
    export type ChannelEnum = 'EMAIL' | 'WHATSAPP' | 'PUSH' | 'SMS';
    export const ChannelEnum = {
        Email: 'EMAIL' as ChannelEnum,
        Whatsapp: 'WHATSAPP' as ChannelEnum,
        Push: 'PUSH' as ChannelEnum,
        Sms: 'SMS' as ChannelEnum
    };
}


