/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailTemplateResponse { 
    templateId: string;
    name: string;
    engine: EmailTemplateResponse.EngineEnum;
    subject?: string | null;
    /**
     * Template content
     */
    body?: string;
    updatedAt: string;
}
export namespace EmailTemplateResponse {
    export type EngineEnum = 'HANDLEBARS' | 'MJML' | 'HTML';
    export const EngineEnum = {
        Handlebars: 'HANDLEBARS' as EngineEnum,
        Mjml: 'MJML' as EngineEnum,
        Html: 'HTML' as EngineEnum
    };
}


