/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EventStatus = 'DRAFT' | 'PUBLISHED' | 'CANCELED' | 'ARCHIVED';

export const EventStatus = {
    Draft: 'DRAFT' as EventStatus,
    Published: 'PUBLISHED' as EventStatus,
    Canceled: 'CANCELED' as EventStatus,
    Archived: 'ARCHIVED' as EventStatus
};

