/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceSummary { 
    invoiceId: string;
    memberId?: string | null;
    status: InvoiceSummary.StatusEnum;
    amount: number;
    currency?: string;
    issuedAt: string;
    dueAt?: string | null;
}
export namespace InvoiceSummary {
    export type StatusEnum = 'DRAFT' | 'ISSUED' | 'PAID' | 'OVERDUE' | 'CANCELED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        Issued: 'ISSUED' as StatusEnum,
        Paid: 'PAID' as StatusEnum,
        Overdue: 'OVERDUE' as StatusEnum,
        Canceled: 'CANCELED' as StatusEnum
    };
}


