/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberStatus } from './memberStatus';


export interface MemberSummary { 
    memberId: string;
    name: string;
    email?: string | null;
    status: MemberStatus;
    categoryId?: string | null;
    segmentId?: string | null;
    communityId?: string | null;
    nucleusId?: string | null;
    createdAt?: string;
}
export namespace MemberSummary {
}


