/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Scope } from './scope';
import { Actor } from './actor';
import { RequestContext } from './requestContext';


export interface MeResponse { 
    actor: Actor;
    context: RequestContext;
    roles: Array<string>;
    scopes: Array<Scope>;
    features?: { [key: string]: boolean; };
}

