/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NpsCampaignSummary { 
    campaignId: string;
    name: string;
    status: NpsCampaignSummary.StatusEnum;
    createdAt: string;
}
export namespace NpsCampaignSummary {
    export type StatusEnum = 'DRAFT' | 'PUBLISHED' | 'CLOSED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        Published: 'PUBLISHED' as StatusEnum,
        Closed: 'CLOSED' as StatusEnum
    };
}


