/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberSummary } from './memberSummary';
import { PagedMeta } from './pagedMeta';


export interface PagedMembersResponse { 
    meta: PagedMeta;
    items: Array<MemberSummary>;
    /**
     * Optional facets for UI filters (counts per status/category/segment)
     */
    facets?: { [key: string]: any; } | null;
}

