/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentSummary { 
    paymentId: string;
    invoiceId?: string | null;
    provider?: string;
    status: PaymentSummary.StatusEnum;
    amount: number;
    currency?: string;
    createdAt: string;
}
export namespace PaymentSummary {
    export type StatusEnum = 'AUTHORIZED' | 'CAPTURED' | 'FAILED' | 'REFUNDED';
    export const StatusEnum = {
        Authorized: 'AUTHORIZED' as StatusEnum,
        Captured: 'CAPTURED' as StatusEnum,
        Failed: 'FAILED' as StatusEnum,
        Refunded: 'REFUNDED' as StatusEnum
    };
}


