/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PointsRecalculateRequest { 
    scope: PointsRecalculateRequest.ScopeEnum;
    memberId?: string | null;
    cycleId?: string | null;
    reason?: string | null;
}
export namespace PointsRecalculateRequest {
    export type ScopeEnum = 'MEMBER' | 'CYCLE' | 'ORG';
    export const ScopeEnum = {
        Member: 'MEMBER' as ScopeEnum,
        Cycle: 'CYCLE' as ScopeEnum,
        Org: 'ORG' as ScopeEnum
    };
}


