/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreviewRequest { 
    templateId: string;
    variables: { [key: string]: any; };
    locale?: PreviewRequest.LocaleEnum | null;
}
export namespace PreviewRequest {
    export type LocaleEnum = 'pt-BR' | 'en' | 'es';
    export const LocaleEnum = {
        PtBr: 'pt-BR' as LocaleEnum,
        En: 'en' as LocaleEnum,
        Es: 'es' as LocaleEnum
    };
}


