/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationSummary { 
    registrationId: string;
    memberId: string;
    status: RegistrationSummary.StatusEnum;
    createdAt: string;
}
export namespace RegistrationSummary {
    export type StatusEnum = 'PENDING' | 'CONFIRMED' | 'CANCELED' | 'WAITLIST';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum,
        Canceled: 'CANCELED' as StatusEnum,
        Waitlist: 'WAITLIST' as StatusEnum
    };
}


