/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StructureNode } from './structureNode';
import { Leader } from './leader';
import { StructureResponse } from './structureResponse';


export interface StructureDetailResponse { 
    structure: StructureResponse;
    nodes?: Array<StructureNode>;
    leaders?: Array<Leader>;
}

