export * from './approvals.service';
import { ApprovalsService } from './approvals.service';
export * from './audit.service';
import { AuditService } from './audit.service';
export * from './billing.service';
import { BillingService } from './billing.service';
export * from './communications.service';
import { CommunicationsService } from './communications.service';
export * from './cycles.service';
import { CyclesService } from './cycles.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './feedback.service';
import { FeedbackService } from './feedback.service';
export * from './members.service';
import { MembersService } from './members.service';
export * from './navigation.service';
import { NavigationService } from './navigation.service';
export * from './points.service';
import { PointsService } from './points.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './structure.service';
import { StructureService } from './structure.service';
export * from './suppliers.service';
import { SuppliersService } from './suppliers.service';
export const APIS = [ApprovalsService, AuditService, BillingService, CommunicationsService, CyclesService, EventsService, FeedbackService, MembersService, NavigationService, PointsService, SessionService, StructureService, SuppliersService];
