/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ApprovalDecisionRequest } from '../model/approvalDecisionRequest';
import { ApprovalDecisionResponse } from '../model/approvalDecisionResponse';
import { ApprovalDetailResponse } from '../model/approvalDetailResponse';
import { ApprovalState } from '../model/approvalState';
import { BulkApprovalDecisionRequest } from '../model/bulkApprovalDecisionRequest';
import { BulkApprovalDecisionResponse } from '../model/bulkApprovalDecisionResponse';
import { ErrorResponse } from '../model/errorResponse';
import { PagedApprovalsResponse } from '../model/pagedApprovalsResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for bulkDecideApprovals operation in ApprovalsService.
 * @export
 * @interface ApprovalsServiceBulkDecideApprovalsRequest
 */
export interface ApprovalsServiceBulkDecideApprovalsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly xOrgId: string

    /**
     * 
     * @type {BulkApprovalDecisionRequest}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly bulkApprovalDecisionRequest: BulkApprovalDecisionRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof ApprovalsServiceBulkDecideApprovals
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for decideApproval operation in ApprovalsService.
 * @export
 * @interface ApprovalsServiceDecideApprovalRequest
 */
export interface ApprovalsServiceDecideApprovalRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly approvalId: string

    /**
     * 
     * @type {ApprovalDecisionRequest}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly approvalDecisionRequest: ApprovalDecisionRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof ApprovalsServiceDecideApproval
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getApproval operation in ApprovalsService.
 * @export
 * @interface ApprovalsServiceGetApprovalRequest
 */
export interface ApprovalsServiceGetApprovalRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly approvalId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof ApprovalsServiceGetApproval
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listApprovals operation in ApprovalsService.
 * @export
 * @interface ApprovalsServiceListApprovalsRequest
 */
export interface ApprovalsServiceListApprovalsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {ApprovalState}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly state?: ApprovalState

    /**
     * 
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly type?: string

    /**
     * 
     * @type {'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'

    /**
     * Free text search
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly size?: number

    /**
     * Sort expression (e.g. createdAt:desc,name:asc)
     * @type {string}
     * @memberof ApprovalsServiceListApprovals
     */
    readonly sort?: string
}


@Injectable()
export class ApprovalsService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Bulk decide approvals (with per-item results)
     * 
     * @param {ApprovalsServiceBulkDecideApprovalsRequest} requestParameters Request parameters.
     */
    public bulkDecideApprovals(requestParameters: ApprovalsServiceBulkDecideApprovalsRequest, ): Observable<AxiosResponse<BulkApprovalDecisionResponse>>;
    public bulkDecideApprovals(requestParameters: ApprovalsServiceBulkDecideApprovalsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    bulkApprovalDecisionRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling bulkDecideApprovals.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling bulkDecideApprovals.');
        }

        if (bulkApprovalDecisionRequest === null || bulkApprovalDecisionRequest === undefined) {
            throw new Error('Required parameter bulkApprovalDecisionRequest was null or undefined when calling bulkDecideApprovals.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<BulkApprovalDecisionResponse>(`${this.basePath}/approvals/bulk-decide`,
                    bulkApprovalDecisionRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Decide an approval request (approve/reject/request changes)
     * 
     * @param {ApprovalsServiceDecideApprovalRequest} requestParameters Request parameters.
     */
    public decideApproval(requestParameters: ApprovalsServiceDecideApprovalRequest, ): Observable<AxiosResponse<ApprovalDecisionResponse>>;
    public decideApproval(requestParameters: ApprovalsServiceDecideApprovalRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    approvalId,
    approvalDecisionRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling decideApproval.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling decideApproval.');
        }

        if (approvalId === null || approvalId === undefined) {
            throw new Error('Required parameter approvalId was null or undefined when calling decideApproval.');
        }

        if (approvalDecisionRequest === null || approvalDecisionRequest === undefined) {
            throw new Error('Required parameter approvalDecisionRequest was null or undefined when calling decideApproval.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<ApprovalDecisionResponse>(`${this.basePath}/approvals/${encodeURIComponent(String(approvalId))}/decide`,
                    approvalDecisionRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get approval request detail
     * 
     * @param {ApprovalsServiceGetApprovalRequest} requestParameters Request parameters.
     */
    public getApproval(requestParameters: ApprovalsServiceGetApprovalRequest, ): Observable<AxiosResponse<ApprovalDetailResponse>>;
    public getApproval(requestParameters: ApprovalsServiceGetApprovalRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    approvalId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getApproval.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getApproval.');
        }

        if (approvalId === null || approvalId === undefined) {
            throw new Error('Required parameter approvalId was null or undefined when calling getApproval.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<ApprovalDetailResponse>(`${this.basePath}/approvals/${encodeURIComponent(String(approvalId))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List approval requests (queue)
     * 
     * @param {ApprovalsServiceListApprovalsRequest} requestParameters Request parameters.
     */
    public listApprovals(requestParameters: ApprovalsServiceListApprovalsRequest, ): Observable<AxiosResponse<PagedApprovalsResponse>>;
    public listApprovals(requestParameters: ApprovalsServiceListApprovalsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    state,
    type,
    priority,
    q,
    page,
    size,
    sort,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listApprovals.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listApprovals.');
        }

        let queryParameters = new URLSearchParams();
        if (state !== undefined && state !== null) {
            queryParameters.append('state', <any>state);
        }
        if (type !== undefined && type !== null) {
            queryParameters.append('type', <any>type);
        }
        if (priority !== undefined && priority !== null) {
            queryParameters.append('priority', <any>priority);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedApprovalsResponse>(`${this.basePath}/approvals`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
