/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { PagedAuditLogsResponse } from '../model/pagedAuditLogsResponse';
import { PagedAuditTrailResponse } from '../model/pagedAuditTrailResponse';
import { PagedControlAlertsResponse } from '../model/pagedControlAlertsResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for getAuditTrail operation in AuditService.
 * @export
 * @interface AuditServiceGetAuditTrailRequest
 */
export interface AuditServiceGetAuditTrailRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly entityType: string

    /**
     * 
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly entityId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly to?: string

    /**
     * 
     * @type {number}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof AuditServiceGetAuditTrail
     */
    readonly size?: number
}

/**
 * Request parameters for listControlAlerts operation in AuditService.
 * @export
 * @interface AuditServiceListControlAlertsRequest
 */
export interface AuditServiceListControlAlertsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof AuditServiceListControlAlerts
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof AuditServiceListControlAlerts
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof AuditServiceListControlAlerts
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof AuditServiceListControlAlerts
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof AuditServiceListControlAlerts
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'}
     * @memberof AuditServiceListControlAlerts
     */
    readonly severity?: 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'

    /**
     * 
     * @type {'OPEN' | 'ACKED' | 'RESOLVED'}
     * @memberof AuditServiceListControlAlerts
     */
    readonly state?: 'OPEN' | 'ACKED' | 'RESOLVED'

    /**
     * 
     * @type {number}
     * @memberof AuditServiceListControlAlerts
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof AuditServiceListControlAlerts
     */
    readonly size?: number
}

/**
 * Request parameters for searchAuditLogs operation in AuditService.
 * @export
 * @interface AuditServiceSearchAuditLogsRequest
 */
export interface AuditServiceSearchAuditLogsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly to?: string

    /**
     * 
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly actorId?: string

    /**
     * 
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly action?: string

    /**
     * Free text search
     * @type {string}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof AuditServiceSearchAuditLogs
     */
    readonly size?: number
}


@Injectable()
export class AuditService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Get audit trail for an entity
     * 
     * @param {AuditServiceGetAuditTrailRequest} requestParameters Request parameters.
     */
    public getAuditTrail(requestParameters: AuditServiceGetAuditTrailRequest, ): Observable<AxiosResponse<PagedAuditTrailResponse>>;
    public getAuditTrail(requestParameters: AuditServiceGetAuditTrailRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    entityType,
    entityId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    from,
    to,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getAuditTrail.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getAuditTrail.');
        }

        if (entityType === null || entityType === undefined) {
            throw new Error('Required parameter entityType was null or undefined when calling getAuditTrail.');
        }

        if (entityId === null || entityId === undefined) {
            throw new Error('Required parameter entityId was null or undefined when calling getAuditTrail.');
        }

        let queryParameters = new URLSearchParams();
        if (entityType !== undefined && entityType !== null) {
            queryParameters.append('entityType', <any>entityType);
        }
        if (entityId !== undefined && entityId !== null) {
            queryParameters.append('entityId', <any>entityId);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedAuditTrailResponse>(`${this.basePath}/audit/trails`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get operational/security alerts (anomaly, policy violations)
     * 
     * @param {AuditServiceListControlAlertsRequest} requestParameters Request parameters.
     */
    public listControlAlerts(requestParameters: AuditServiceListControlAlertsRequest, ): Observable<AxiosResponse<PagedControlAlertsResponse>>;
    public listControlAlerts(requestParameters: AuditServiceListControlAlertsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    severity,
    state,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listControlAlerts.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listControlAlerts.');
        }

        let queryParameters = new URLSearchParams();
        if (severity !== undefined && severity !== null) {
            queryParameters.append('severity', <any>severity);
        }
        if (state !== undefined && state !== null) {
            queryParameters.append('state', <any>state);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedControlAlertsResponse>(`${this.basePath}/controls/alerts`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Search admin logs (UI and/or core logs unified view)
     * 
     * @param {AuditServiceSearchAuditLogsRequest} requestParameters Request parameters.
     */
    public searchAuditLogs(requestParameters: AuditServiceSearchAuditLogsRequest, ): Observable<AxiosResponse<PagedAuditLogsResponse>>;
    public searchAuditLogs(requestParameters: AuditServiceSearchAuditLogsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    from,
    to,
    actorId,
    action,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling searchAuditLogs.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling searchAuditLogs.');
        }

        let queryParameters = new URLSearchParams();
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (actorId !== undefined && actorId !== null) {
            queryParameters.append('actorId', <any>actorId);
        }
        if (action !== undefined && action !== null) {
            queryParameters.append('action', <any>action);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedAuditLogsResponse>(`${this.basePath}/audit/logs`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
