/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AsyncJobAcceptedResponse } from '../model/asyncJobAcceptedResponse';
import { BillingReconcileRequest } from '../model/billingReconcileRequest';
import { PagedInvoicesResponse } from '../model/pagedInvoicesResponse';
import { PagedPaymentsResponse } from '../model/pagedPaymentsResponse';
import { RefundRequest } from '../model/refundRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for listInvoices operation in BillingService.
 * @export
 * @interface BillingServiceListInvoicesRequest
 */
export interface BillingServiceListInvoicesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof BillingServiceListInvoices
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'DRAFT' | 'ISSUED' | 'PAID' | 'OVERDUE' | 'CANCELED'}
     * @memberof BillingServiceListInvoices
     */
    readonly status?: 'DRAFT' | 'ISSUED' | 'PAID' | 'OVERDUE' | 'CANCELED'

    /**
     * 
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly memberId?: string

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof BillingServiceListInvoices
     */
    readonly to?: string

    /**
     * 
     * @type {number}
     * @memberof BillingServiceListInvoices
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof BillingServiceListInvoices
     */
    readonly size?: number
}

/**
 * Request parameters for listPayments operation in BillingService.
 * @export
 * @interface BillingServiceListPaymentsRequest
 */
export interface BillingServiceListPaymentsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof BillingServiceListPayments
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'AUTHORIZED' | 'CAPTURED' | 'FAILED' | 'REFUNDED'}
     * @memberof BillingServiceListPayments
     */
    readonly status?: 'AUTHORIZED' | 'CAPTURED' | 'FAILED' | 'REFUNDED'

    /**
     * 
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly provider?: string

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof BillingServiceListPayments
     */
    readonly to?: string

    /**
     * 
     * @type {number}
     * @memberof BillingServiceListPayments
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof BillingServiceListPayments
     */
    readonly size?: number
}

/**
 * Request parameters for reconcileBilling operation in BillingService.
 * @export
 * @interface BillingServiceReconcileBillingRequest
 */
export interface BillingServiceReconcileBillingRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof BillingServiceReconcileBilling
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof BillingServiceReconcileBilling
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof BillingServiceReconcileBilling
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof BillingServiceReconcileBilling
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof BillingServiceReconcileBilling
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {BillingReconcileRequest}
     * @memberof BillingServiceReconcileBilling
     */
    readonly billingReconcileRequest?: BillingReconcileRequest
}

/**
 * Request parameters for refundPayment operation in BillingService.
 * @export
 * @interface BillingServiceRefundPaymentRequest
 */
export interface BillingServiceRefundPaymentRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof BillingServiceRefundPayment
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof BillingServiceRefundPayment
     */
    readonly xOrgId: string

    /**
     * 
     * @type {RefundRequest}
     * @memberof BillingServiceRefundPayment
     */
    readonly refundRequest: RefundRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof BillingServiceRefundPayment
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof BillingServiceRefundPayment
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof BillingServiceRefundPayment
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class BillingService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * List invoices
     * 
     * @param {BillingServiceListInvoicesRequest} requestParameters Request parameters.
     */
    public listInvoices(requestParameters: BillingServiceListInvoicesRequest, ): Observable<AxiosResponse<PagedInvoicesResponse>>;
    public listInvoices(requestParameters: BillingServiceListInvoicesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    memberId,
    from,
    to,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listInvoices.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listInvoices.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (memberId !== undefined && memberId !== null) {
            queryParameters.append('memberId', <any>memberId);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedInvoicesResponse>(`${this.basePath}/billing/invoices`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List payments
     * 
     * @param {BillingServiceListPaymentsRequest} requestParameters Request parameters.
     */
    public listPayments(requestParameters: BillingServiceListPaymentsRequest, ): Observable<AxiosResponse<PagedPaymentsResponse>>;
    public listPayments(requestParameters: BillingServiceListPaymentsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    provider,
    from,
    to,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listPayments.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listPayments.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (provider !== undefined && provider !== null) {
            queryParameters.append('provider', <any>provider);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedPaymentsResponse>(`${this.basePath}/billing/payments`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Request billing reconciliation (async)
     * 
     * @param {BillingServiceReconcileBillingRequest} requestParameters Request parameters.
     */
    public reconcileBilling(requestParameters: BillingServiceReconcileBillingRequest, ): Observable<AxiosResponse<AsyncJobAcceptedResponse>>;
    public reconcileBilling(requestParameters: BillingServiceReconcileBillingRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    billingReconcileRequest,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling reconcileBilling.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling reconcileBilling.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AsyncJobAcceptedResponse>(`${this.basePath}/billing/reconcile`,
                    billingReconcileRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Request a refund
     * 
     * @param {BillingServiceRefundPaymentRequest} requestParameters Request parameters.
     */
    public refundPayment(requestParameters: BillingServiceRefundPaymentRequest, ): Observable<AxiosResponse<AsyncJobAcceptedResponse>>;
    public refundPayment(requestParameters: BillingServiceRefundPaymentRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    refundRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling refundPayment.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling refundPayment.');
        }

        if (refundRequest === null || refundRequest === undefined) {
            throw new Error('Required parameter refundRequest was null or undefined when calling refundPayment.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AsyncJobAcceptedResponse>(`${this.basePath}/billing/refund`,
                    refundRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
