/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateNewsletterRequest } from '../model/createNewsletterRequest';
import { CreateNotificationRequest } from '../model/createNotificationRequest';
import { EmailTemplateResponse } from '../model/emailTemplateResponse';
import { EmailTemplatesResponse } from '../model/emailTemplatesResponse';
import { NewsletterResponse } from '../model/newsletterResponse';
import { NotificationResponse } from '../model/notificationResponse';
import { PagedNewslettersResponse } from '../model/pagedNewslettersResponse';
import { PagedNotificationsResponse } from '../model/pagedNotificationsResponse';
import { PreviewRequest } from '../model/previewRequest';
import { PreviewResponse } from '../model/previewResponse';
import { UpdateEmailTemplateRequest } from '../model/updateEmailTemplateRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createNewsletter operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceCreateNewsletterRequest
 */
export interface CommunicationsServiceCreateNewsletterRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateNewsletterRequest}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly createNewsletterRequest: CreateNewsletterRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceCreateNewsletter
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for createNotification operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceCreateNotificationRequest
 */
export interface CommunicationsServiceCreateNotificationRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateNotificationRequest}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly createNotificationRequest: CreateNotificationRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceCreateNotification
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listEmailTemplates operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceListEmailTemplatesRequest
 */
export interface CommunicationsServiceListEmailTemplatesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceListEmailTemplates
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceListEmailTemplates
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceListEmailTemplates
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceListEmailTemplates
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceListEmailTemplates
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listNewsletters operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceListNewslettersRequest
 */
export interface CommunicationsServiceListNewslettersRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'DRAFT' | 'SCHEDULED' | 'SENDING' | 'SENT' | 'FAILED'}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly status?: 'DRAFT' | 'SCHEDULED' | 'SENDING' | 'SENT' | 'FAILED'

    /**
     * Free text search
     * @type {string}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof CommunicationsServiceListNewsletters
     */
    readonly size?: number
}

/**
 * Request parameters for listNotifications operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceListNotificationsRequest
 */
export interface CommunicationsServiceListNotificationsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'DRAFT' | 'SCHEDULED' | 'SENDING' | 'SENT' | 'FAILED'}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly status?: 'DRAFT' | 'SCHEDULED' | 'SENDING' | 'SENT' | 'FAILED'

    /**
     * Free text search
     * @type {string}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof CommunicationsServiceListNotifications
     */
    readonly size?: number
}

/**
 * Request parameters for previewCommunication operation in CommunicationsService.
 * @export
 * @interface CommunicationsServicePreviewCommunicationRequest
 */
export interface CommunicationsServicePreviewCommunicationRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly xOrgId: string

    /**
     * 
     * @type {PreviewRequest}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly previewRequest: PreviewRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServicePreviewCommunication
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for updateEmailTemplate operation in CommunicationsService.
 * @export
 * @interface CommunicationsServiceUpdateEmailTemplateRequest
 */
export interface CommunicationsServiceUpdateEmailTemplateRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly templateId: string

    /**
     * 
     * @type {UpdateEmailTemplateRequest}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly updateEmailTemplateRequest: UpdateEmailTemplateRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CommunicationsServiceUpdateEmailTemplate
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class CommunicationsService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create newsletter
     * 
     * @param {CommunicationsServiceCreateNewsletterRequest} requestParameters Request parameters.
     */
    public createNewsletter(requestParameters: CommunicationsServiceCreateNewsletterRequest, ): Observable<AxiosResponse<NewsletterResponse>>;
    public createNewsletter(requestParameters: CommunicationsServiceCreateNewsletterRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createNewsletterRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createNewsletter.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createNewsletter.');
        }

        if (createNewsletterRequest === null || createNewsletterRequest === undefined) {
            throw new Error('Required parameter createNewsletterRequest was null or undefined when calling createNewsletter.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<NewsletterResponse>(`${this.basePath}/comms/newsletters`,
                    createNewsletterRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Create notification campaign
     * 
     * @param {CommunicationsServiceCreateNotificationRequest} requestParameters Request parameters.
     */
    public createNotification(requestParameters: CommunicationsServiceCreateNotificationRequest, ): Observable<AxiosResponse<NotificationResponse>>;
    public createNotification(requestParameters: CommunicationsServiceCreateNotificationRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createNotificationRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createNotification.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createNotification.');
        }

        if (createNotificationRequest === null || createNotificationRequest === undefined) {
            throw new Error('Required parameter createNotificationRequest was null or undefined when calling createNotification.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<NotificationResponse>(`${this.basePath}/comms/notifications`,
                    createNotificationRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List email templates
     * 
     * @param {CommunicationsServiceListEmailTemplatesRequest} requestParameters Request parameters.
     */
    public listEmailTemplates(requestParameters: CommunicationsServiceListEmailTemplatesRequest, ): Observable<AxiosResponse<EmailTemplatesResponse>>;
    public listEmailTemplates(requestParameters: CommunicationsServiceListEmailTemplatesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listEmailTemplates.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listEmailTemplates.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<EmailTemplatesResponse>(`${this.basePath}/comms/email-templates`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List newsletters
     * 
     * @param {CommunicationsServiceListNewslettersRequest} requestParameters Request parameters.
     */
    public listNewsletters(requestParameters: CommunicationsServiceListNewslettersRequest, ): Observable<AxiosResponse<PagedNewslettersResponse>>;
    public listNewsletters(requestParameters: CommunicationsServiceListNewslettersRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listNewsletters.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listNewsletters.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedNewslettersResponse>(`${this.basePath}/comms/newsletters`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List notifications campaigns
     * 
     * @param {CommunicationsServiceListNotificationsRequest} requestParameters Request parameters.
     */
    public listNotifications(requestParameters: CommunicationsServiceListNotificationsRequest, ): Observable<AxiosResponse<PagedNotificationsResponse>>;
    public listNotifications(requestParameters: CommunicationsServiceListNotificationsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listNotifications.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listNotifications.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedNotificationsResponse>(`${this.basePath}/comms/notifications`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Render a preview for a template with variables (safe preview)
     * 
     * @param {CommunicationsServicePreviewCommunicationRequest} requestParameters Request parameters.
     */
    public previewCommunication(requestParameters: CommunicationsServicePreviewCommunicationRequest, ): Observable<AxiosResponse<PreviewResponse>>;
    public previewCommunication(requestParameters: CommunicationsServicePreviewCommunicationRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    previewRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling previewCommunication.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling previewCommunication.');
        }

        if (previewRequest === null || previewRequest === undefined) {
            throw new Error('Required parameter previewRequest was null or undefined when calling previewCommunication.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<PreviewResponse>(`${this.basePath}/comms/preview`,
                    previewRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update email template
     * 
     * @param {CommunicationsServiceUpdateEmailTemplateRequest} requestParameters Request parameters.
     */
    public updateEmailTemplate(requestParameters: CommunicationsServiceUpdateEmailTemplateRequest, ): Observable<AxiosResponse<EmailTemplateResponse>>;
    public updateEmailTemplate(requestParameters: CommunicationsServiceUpdateEmailTemplateRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    templateId,
    updateEmailTemplateRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updateEmailTemplate.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updateEmailTemplate.');
        }

        if (templateId === null || templateId === undefined) {
            throw new Error('Required parameter templateId was null or undefined when calling updateEmailTemplate.');
        }

        if (updateEmailTemplateRequest === null || updateEmailTemplateRequest === undefined) {
            throw new Error('Required parameter updateEmailTemplateRequest was null or undefined when calling updateEmailTemplate.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<EmailTemplateResponse>(`${this.basePath}/comms/email-templates/${encodeURIComponent(String(templateId))}`,
                    updateEmailTemplateRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
