/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateCycleRequest } from '../model/createCycleRequest';
import { CycleDetailResponse } from '../model/cycleDetailResponse';
import { CycleResponse } from '../model/cycleResponse';
import { CycleStatus } from '../model/cycleStatus';
import { CyclesResponse } from '../model/cyclesResponse';
import { EnableBlocksRequest } from '../model/enableBlocksRequest';
import { EnableBlocksResponse } from '../model/enableBlocksResponse';
import { ErrorResponse } from '../model/errorResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createCycle operation in CyclesService.
 * @export
 * @interface CyclesServiceCreateCycleRequest
 */
export interface CyclesServiceCreateCycleRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CyclesServiceCreateCycle
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CyclesServiceCreateCycle
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateCycleRequest}
     * @memberof CyclesServiceCreateCycle
     */
    readonly createCycleRequest: CreateCycleRequest

    /**
     * Client correlation id
     * @type {string}
     * @memberof CyclesServiceCreateCycle
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CyclesServiceCreateCycle
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getCycle operation in CyclesService.
 * @export
 * @interface CyclesServiceGetCycleRequest
 */
export interface CyclesServiceGetCycleRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CyclesServiceGetCycle
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CyclesServiceGetCycle
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof CyclesServiceGetCycle
     */
    readonly cycleId: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CyclesServiceGetCycle
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CyclesServiceGetCycle
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof CyclesServiceGetCycle
     */
    readonly expand?: Array<string>
}

/**
 * Request parameters for listCycles operation in CyclesService.
 * @export
 * @interface CyclesServiceListCyclesRequest
 */
export interface CyclesServiceListCyclesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CyclesServiceListCycles
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CyclesServiceListCycles
     */
    readonly xOrgId: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CyclesServiceListCycles
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CyclesServiceListCycles
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {CycleStatus}
     * @memberof CyclesServiceListCycles
     */
    readonly status?: CycleStatus
}

/**
 * Request parameters for publishCycle operation in CyclesService.
 * @export
 * @interface CyclesServicePublishCycleRequest
 */
export interface CyclesServicePublishCycleRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CyclesServicePublishCycle
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CyclesServicePublishCycle
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof CyclesServicePublishCycle
     */
    readonly cycleId: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof CyclesServicePublishCycle
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CyclesServicePublishCycle
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for setCycleEnabledBlocks operation in CyclesService.
 * @export
 * @interface CyclesServiceSetCycleEnabledBlocksRequest
 */
export interface CyclesServiceSetCycleEnabledBlocksRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly cycleId: string

    /**
     * 
     * @type {EnableBlocksRequest}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly enableBlocksRequest: EnableBlocksRequest

    /**
     * Client correlation id
     * @type {string}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof CyclesServiceSetCycleEnabledBlocks
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class CyclesService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create cycle
     * 
     * @param {CyclesServiceCreateCycleRequest} requestParameters Request parameters.
     */
    public createCycle(requestParameters: CyclesServiceCreateCycleRequest, ): Observable<AxiosResponse<CycleResponse>>;
    public createCycle(requestParameters: CyclesServiceCreateCycleRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createCycleRequest,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createCycle.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createCycle.');
        }

        if (createCycleRequest === null || createCycleRequest === undefined) {
            throw new Error('Required parameter createCycleRequest was null or undefined when calling createCycle.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CycleResponse>(`${this.basePath}/cycles`,
                    createCycleRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get cycle detail (with phases and enabled blocks)
     * 
     * @param {CyclesServiceGetCycleRequest} requestParameters Request parameters.
     */
    public getCycle(requestParameters: CyclesServiceGetCycleRequest, ): Observable<AxiosResponse<CycleDetailResponse>>;
    public getCycle(requestParameters: CyclesServiceGetCycleRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    cycleId,
    xRequestId,
    acceptLanguage,
    expand,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getCycle.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getCycle.');
        }

        if (cycleId === null || cycleId === undefined) {
            throw new Error('Required parameter cycleId was null or undefined when calling getCycle.');
        }

        let queryParameters = new URLSearchParams();
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<CycleDetailResponse>(`${this.basePath}/cycles/${encodeURIComponent(String(cycleId))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List cycles
     * 
     * @param {CyclesServiceListCyclesRequest} requestParameters Request parameters.
     */
    public listCycles(requestParameters: CyclesServiceListCyclesRequest, ): Observable<AxiosResponse<CyclesResponse>>;
    public listCycles(requestParameters: CyclesServiceListCyclesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xRequestId,
    acceptLanguage,
    status,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listCycles.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listCycles.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<CyclesResponse>(`${this.basePath}/cycles`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Publish cycle (make it active/usable)
     * 
     * @param {CyclesServicePublishCycleRequest} requestParameters Request parameters.
     */
    public publishCycle(requestParameters: CyclesServicePublishCycleRequest, ): Observable<AxiosResponse<CycleResponse>>;
    public publishCycle(requestParameters: CyclesServicePublishCycleRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    cycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling publishCycle.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling publishCycle.');
        }

        if (cycleId === null || cycleId === undefined) {
            throw new Error('Required parameter cycleId was null or undefined when calling publishCycle.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CycleResponse>(`${this.basePath}/cycles/${encodeURIComponent(String(cycleId))}/publish`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update enabled blocks matrix for the cycle/phases
     * 
     * @param {CyclesServiceSetCycleEnabledBlocksRequest} requestParameters Request parameters.
     */
    public setCycleEnabledBlocks(requestParameters: CyclesServiceSetCycleEnabledBlocksRequest, ): Observable<AxiosResponse<EnableBlocksResponse>>;
    public setCycleEnabledBlocks(requestParameters: CyclesServiceSetCycleEnabledBlocksRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    cycleId,
    enableBlocksRequest,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling setCycleEnabledBlocks.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling setCycleEnabledBlocks.');
        }

        if (cycleId === null || cycleId === undefined) {
            throw new Error('Required parameter cycleId was null or undefined when calling setCycleEnabledBlocks.');
        }

        if (enableBlocksRequest === null || enableBlocksRequest === undefined) {
            throw new Error('Required parameter enableBlocksRequest was null or undefined when calling setCycleEnabledBlocks.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<EnableBlocksResponse>(`${this.basePath}/cycles/${encodeURIComponent(String(cycleId))}/enable-blocks`,
                    enableBlocksRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
