/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateEventRequest } from '../model/createEventRequest';
import { ErrorResponse } from '../model/errorResponse';
import { EventDetailResponse } from '../model/eventDetailResponse';
import { EventPermissionsRequest } from '../model/eventPermissionsRequest';
import { EventPermissionsResponse } from '../model/eventPermissionsResponse';
import { EventResponse } from '../model/eventResponse';
import { EventStatus } from '../model/eventStatus';
import { PagedEventsResponse } from '../model/pagedEventsResponse';
import { PagedRegistrationsResponse } from '../model/pagedRegistrationsResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createEvent operation in EventsService.
 * @export
 * @interface EventsServiceCreateEventRequest
 */
export interface EventsServiceCreateEventRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServiceCreateEvent
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServiceCreateEvent
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateEventRequest}
     * @memberof EventsServiceCreateEvent
     */
    readonly createEventRequest: CreateEventRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServiceCreateEvent
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServiceCreateEvent
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServiceCreateEvent
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getEvent operation in EventsService.
 * @export
 * @interface EventsServiceGetEventRequest
 */
export interface EventsServiceGetEventRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServiceGetEvent
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServiceGetEvent
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof EventsServiceGetEvent
     */
    readonly eventId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServiceGetEvent
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServiceGetEvent
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServiceGetEvent
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof EventsServiceGetEvent
     */
    readonly expand?: Array<string>
}

/**
 * Request parameters for listEventRegistrations operation in EventsService.
 * @export
 * @interface EventsServiceListEventRegistrationsRequest
 */
export interface EventsServiceListEventRegistrationsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly eventId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {'PENDING' | 'CONFIRMED' | 'CANCELED' | 'WAITLIST'}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly status?: 'PENDING' | 'CONFIRMED' | 'CANCELED' | 'WAITLIST'

    /**
     * 
     * @type {number}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof EventsServiceListEventRegistrations
     */
    readonly size?: number
}

/**
 * Request parameters for listEvents operation in EventsService.
 * @export
 * @interface EventsServiceListEventsRequest
 */
export interface EventsServiceListEventsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServiceListEvents
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {EventStatus}
     * @memberof EventsServiceListEvents
     */
    readonly status?: EventStatus

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly to?: string

    /**
     * Free text search
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof EventsServiceListEvents
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof EventsServiceListEvents
     */
    readonly size?: number

    /**
     * Sort expression (e.g. createdAt:desc,name:asc)
     * @type {string}
     * @memberof EventsServiceListEvents
     */
    readonly sort?: string
}

/**
 * Request parameters for publishEvent operation in EventsService.
 * @export
 * @interface EventsServicePublishEventRequest
 */
export interface EventsServicePublishEventRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServicePublishEvent
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServicePublishEvent
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof EventsServicePublishEvent
     */
    readonly eventId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServicePublishEvent
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServicePublishEvent
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServicePublishEvent
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for updateEventPermissions operation in EventsService.
 * @export
 * @interface EventsServiceUpdateEventPermissionsRequest
 */
export interface EventsServiceUpdateEventPermissionsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly eventId: string

    /**
     * 
     * @type {EventPermissionsRequest}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly eventPermissionsRequest: EventPermissionsRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof EventsServiceUpdateEventPermissions
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class EventsService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create event
     * 
     * @param {EventsServiceCreateEventRequest} requestParameters Request parameters.
     */
    public createEvent(requestParameters: EventsServiceCreateEventRequest, ): Observable<AxiosResponse<EventResponse>>;
    public createEvent(requestParameters: EventsServiceCreateEventRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createEventRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createEvent.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createEvent.');
        }

        if (createEventRequest === null || createEventRequest === undefined) {
            throw new Error('Required parameter createEventRequest was null or undefined when calling createEvent.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<EventResponse>(`${this.basePath}/events`,
                    createEventRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get event detail
     * 
     * @param {EventsServiceGetEventRequest} requestParameters Request parameters.
     */
    public getEvent(requestParameters: EventsServiceGetEventRequest, ): Observable<AxiosResponse<EventDetailResponse>>;
    public getEvent(requestParameters: EventsServiceGetEventRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    eventId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    expand,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getEvent.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getEvent.');
        }

        if (eventId === null || eventId === undefined) {
            throw new Error('Required parameter eventId was null or undefined when calling getEvent.');
        }

        let queryParameters = new URLSearchParams();
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<EventDetailResponse>(`${this.basePath}/events/${encodeURIComponent(String(eventId))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List event registrations
     * 
     * @param {EventsServiceListEventRegistrationsRequest} requestParameters Request parameters.
     */
    public listEventRegistrations(requestParameters: EventsServiceListEventRegistrationsRequest, ): Observable<AxiosResponse<PagedRegistrationsResponse>>;
    public listEventRegistrations(requestParameters: EventsServiceListEventRegistrationsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    eventId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listEventRegistrations.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listEventRegistrations.');
        }

        if (eventId === null || eventId === undefined) {
            throw new Error('Required parameter eventId was null or undefined when calling listEventRegistrations.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedRegistrationsResponse>(`${this.basePath}/events/${encodeURIComponent(String(eventId))}/registrations`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List events
     * 
     * @param {EventsServiceListEventsRequest} requestParameters Request parameters.
     */
    public listEvents(requestParameters: EventsServiceListEventsRequest, ): Observable<AxiosResponse<PagedEventsResponse>>;
    public listEvents(requestParameters: EventsServiceListEventsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    status,
    from,
    to,
    q,
    page,
    size,
    sort,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listEvents.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listEvents.');
        }

        let queryParameters = new URLSearchParams();
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedEventsResponse>(`${this.basePath}/events`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Publish event
     * 
     * @param {EventsServicePublishEventRequest} requestParameters Request parameters.
     */
    public publishEvent(requestParameters: EventsServicePublishEventRequest, ): Observable<AxiosResponse<EventResponse>>;
    public publishEvent(requestParameters: EventsServicePublishEventRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    eventId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling publishEvent.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling publishEvent.');
        }

        if (eventId === null || eventId === undefined) {
            throw new Error('Required parameter eventId was null or undefined when calling publishEvent.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<EventResponse>(`${this.basePath}/events/${encodeURIComponent(String(eventId))}/publish`,
                    null,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update event permissions/policies
     * 
     * @param {EventsServiceUpdateEventPermissionsRequest} requestParameters Request parameters.
     */
    public updateEventPermissions(requestParameters: EventsServiceUpdateEventPermissionsRequest, ): Observable<AxiosResponse<EventPermissionsResponse>>;
    public updateEventPermissions(requestParameters: EventsServiceUpdateEventPermissionsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    eventId,
    eventPermissionsRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updateEventPermissions.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updateEventPermissions.');
        }

        if (eventId === null || eventId === undefined) {
            throw new Error('Required parameter eventId was null or undefined when calling updateEventPermissions.');
        }

        if (eventPermissionsRequest === null || eventPermissionsRequest === undefined) {
            throw new Error('Required parameter eventPermissionsRequest was null or undefined when calling updateEventPermissions.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<EventPermissionsResponse>(`${this.basePath}/events/${encodeURIComponent(String(eventId))}/permissions`,
                    eventPermissionsRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
