/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateNpsCampaignRequest } from '../model/createNpsCampaignRequest';
import { NpsCampaignResponse } from '../model/npsCampaignResponse';
import { NpsResultsResponse } from '../model/npsResultsResponse';
import { PagedNpsCampaignsResponse } from '../model/pagedNpsCampaignsResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createNpsCampaign operation in FeedbackService.
 * @export
 * @interface FeedbackServiceCreateNpsCampaignRequest
 */
export interface FeedbackServiceCreateNpsCampaignRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateNpsCampaignRequest}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly createNpsCampaignRequest: CreateNpsCampaignRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof FeedbackServiceCreateNpsCampaign
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getNpsResults operation in FeedbackService.
 * @export
 * @interface FeedbackServiceGetNpsResultsRequest
 */
export interface FeedbackServiceGetNpsResultsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly campaignId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof FeedbackServiceGetNpsResults
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listNpsCampaigns operation in FeedbackService.
 * @export
 * @interface FeedbackServiceListNpsCampaignsRequest
 */
export interface FeedbackServiceListNpsCampaignsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {number}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof FeedbackServiceListNpsCampaigns
     */
    readonly size?: number
}


@Injectable()
export class FeedbackService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create NPS campaign
     * 
     * @param {FeedbackServiceCreateNpsCampaignRequest} requestParameters Request parameters.
     */
    public createNpsCampaign(requestParameters: FeedbackServiceCreateNpsCampaignRequest, ): Observable<AxiosResponse<NpsCampaignResponse>>;
    public createNpsCampaign(requestParameters: FeedbackServiceCreateNpsCampaignRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createNpsCampaignRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createNpsCampaign.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createNpsCampaign.');
        }

        if (createNpsCampaignRequest === null || createNpsCampaignRequest === undefined) {
            throw new Error('Required parameter createNpsCampaignRequest was null or undefined when calling createNpsCampaign.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<NpsCampaignResponse>(`${this.basePath}/feedback/nps/campaigns`,
                    createNpsCampaignRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get NPS campaign results (aggregates)
     * 
     * @param {FeedbackServiceGetNpsResultsRequest} requestParameters Request parameters.
     */
    public getNpsResults(requestParameters: FeedbackServiceGetNpsResultsRequest, ): Observable<AxiosResponse<NpsResultsResponse>>;
    public getNpsResults(requestParameters: FeedbackServiceGetNpsResultsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    campaignId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getNpsResults.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getNpsResults.');
        }

        if (campaignId === null || campaignId === undefined) {
            throw new Error('Required parameter campaignId was null or undefined when calling getNpsResults.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<NpsResultsResponse>(`${this.basePath}/feedback/nps/${encodeURIComponent(String(campaignId))}/results`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List NPS campaigns
     * 
     * @param {FeedbackServiceListNpsCampaignsRequest} requestParameters Request parameters.
     */
    public listNpsCampaigns(requestParameters: FeedbackServiceListNpsCampaignsRequest, ): Observable<AxiosResponse<PagedNpsCampaignsResponse>>;
    public listNpsCampaigns(requestParameters: FeedbackServiceListNpsCampaignsRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listNpsCampaigns.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listNpsCampaigns.');
        }

        let queryParameters = new URLSearchParams();
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedNpsCampaignsResponse>(`${this.basePath}/feedback/nps/campaigns`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
