/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ChangeMemberStatusRequest } from '../model/changeMemberStatusRequest';
import { ErrorResponse } from '../model/errorResponse';
import { MemberAssignRequest } from '../model/memberAssignRequest';
import { MemberAssignResponse } from '../model/memberAssignResponse';
import { MemberDetailResponse } from '../model/memberDetailResponse';
import { MemberStatus } from '../model/memberStatus';
import { MemberStatusChangeResponse } from '../model/memberStatusChangeResponse';
import { PagedMemberHistoryResponse } from '../model/pagedMemberHistoryResponse';
import { PagedMembersResponse } from '../model/pagedMembersResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for assignMember operation in MembersService.
 * @export
 * @interface MembersServiceAssignMemberRequest
 */
export interface MembersServiceAssignMemberRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof MembersServiceAssignMember
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof MembersServiceAssignMember
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceAssignMember
     */
    readonly memberId: string

    /**
     * 
     * @type {MemberAssignRequest}
     * @memberof MembersServiceAssignMember
     */
    readonly memberAssignRequest: MemberAssignRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof MembersServiceAssignMember
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof MembersServiceAssignMember
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof MembersServiceAssignMember
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for changeMemberStatus operation in MembersService.
 * @export
 * @interface MembersServiceChangeMemberStatusRequest
 */
export interface MembersServiceChangeMemberStatusRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly memberId: string

    /**
     * 
     * @type {ChangeMemberStatusRequest}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly changeMemberStatusRequest: ChangeMemberStatusRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof MembersServiceChangeMemberStatus
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getMember operation in MembersService.
 * @export
 * @interface MembersServiceGetMemberRequest
 */
export interface MembersServiceGetMemberRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof MembersServiceGetMember
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof MembersServiceGetMember
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceGetMember
     */
    readonly memberId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof MembersServiceGetMember
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof MembersServiceGetMember
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof MembersServiceGetMember
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Projection/view model hint
     * @type {'compact' | 'default' | 'full'}
     * @memberof MembersServiceGetMember
     */
    readonly view?: 'compact' | 'default' | 'full'

    /**
     * Include optional sections, comma-separated (e.g. include&#x3D;pointsSummary,approvalsHistory)
     * @type {Array<string>}
     * @memberof MembersServiceGetMember
     */
    readonly include?: Array<string>

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof MembersServiceGetMember
     */
    readonly expand?: Array<string>
}

/**
 * Request parameters for getMemberHistory operation in MembersService.
 * @export
 * @interface MembersServiceGetMemberHistoryRequest
 */
export interface MembersServiceGetMemberHistoryRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly memberId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly to?: string

    /**
     * 
     * @type {number}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof MembersServiceGetMemberHistory
     */
    readonly size?: number
}

/**
 * Request parameters for listMembers operation in MembersService.
 * @export
 * @interface MembersServiceListMembersRequest
 */
export interface MembersServiceListMembersRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof MembersServiceListMembers
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Free text search
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly q?: string

    /**
     * 
     * @type {MemberStatus}
     * @memberof MembersServiceListMembers
     */
    readonly status?: MemberStatus

    /**
     * 
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly categoryId?: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly segmentId?: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly communityId?: string

    /**
     * 
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly nucleusId?: string

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly to?: string

    /**
     * Projection/view model hint
     * @type {'compact' | 'default' | 'full'}
     * @memberof MembersServiceListMembers
     */
    readonly view?: 'compact' | 'default' | 'full'

    /**
     * Include optional sections, comma-separated (e.g. include&#x3D;pointsSummary,approvalsHistory)
     * @type {Array<string>}
     * @memberof MembersServiceListMembers
     */
    readonly include?: Array<string>

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof MembersServiceListMembers
     */
    readonly expand?: Array<string>

    /**
     * 
     * @type {number}
     * @memberof MembersServiceListMembers
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof MembersServiceListMembers
     */
    readonly size?: number

    /**
     * Sort expression (e.g. createdAt:desc,name:asc)
     * @type {string}
     * @memberof MembersServiceListMembers
     */
    readonly sort?: string
}


@Injectable()
export class MembersService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Assign member to structure/community/nucleus/position
     * 
     * @param {MembersServiceAssignMemberRequest} requestParameters Request parameters.
     */
    public assignMember(requestParameters: MembersServiceAssignMemberRequest, ): Observable<AxiosResponse<MemberAssignResponse>>;
    public assignMember(requestParameters: MembersServiceAssignMemberRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    memberId,
    memberAssignRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling assignMember.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling assignMember.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling assignMember.');
        }

        if (memberAssignRequest === null || memberAssignRequest === undefined) {
            throw new Error('Required parameter memberAssignRequest was null or undefined when calling assignMember.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<MemberAssignResponse>(`${this.basePath}/members/${encodeURIComponent(String(memberId))}/assign`,
                    memberAssignRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Change member status (admin action)
     * 
     * @param {MembersServiceChangeMemberStatusRequest} requestParameters Request parameters.
     */
    public changeMemberStatus(requestParameters: MembersServiceChangeMemberStatusRequest, ): Observable<AxiosResponse<MemberStatusChangeResponse>>;
    public changeMemberStatus(requestParameters: MembersServiceChangeMemberStatusRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    memberId,
    changeMemberStatusRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling changeMemberStatus.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling changeMemberStatus.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling changeMemberStatus.');
        }

        if (changeMemberStatusRequest === null || changeMemberStatusRequest === undefined) {
            throw new Error('Required parameter changeMemberStatusRequest was null or undefined when calling changeMemberStatus.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<MemberStatusChangeResponse>(`${this.basePath}/members/${encodeURIComponent(String(memberId))}/status`,
                    changeMemberStatusRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get member detail with optional expansions (screen-ready)
     * 
     * @param {MembersServiceGetMemberRequest} requestParameters Request parameters.
     */
    public getMember(requestParameters: MembersServiceGetMemberRequest, ): Observable<AxiosResponse<MemberDetailResponse>>;
    public getMember(requestParameters: MembersServiceGetMemberRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    memberId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    view,
    include,
    expand,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getMember.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getMember.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling getMember.');
        }

        let queryParameters = new URLSearchParams();
        if (view !== undefined && view !== null) {
            queryParameters.append('view', <any>view);
        }
        if (include) {
            queryParameters['include'] = include.join(COLLECTION_FORMATS['csv']);
        }
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MemberDetailResponse>(`${this.basePath}/members/${encodeURIComponent(String(memberId))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get member administrative history (approvals, status changes, key actions)
     * 
     * @param {MembersServiceGetMemberHistoryRequest} requestParameters Request parameters.
     */
    public getMemberHistory(requestParameters: MembersServiceGetMemberHistoryRequest, ): Observable<AxiosResponse<PagedMemberHistoryResponse>>;
    public getMemberHistory(requestParameters: MembersServiceGetMemberHistoryRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    memberId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    from,
    to,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getMemberHistory.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getMemberHistory.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling getMemberHistory.');
        }

        let queryParameters = new URLSearchParams();
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedMemberHistoryResponse>(`${this.basePath}/members/${encodeURIComponent(String(memberId))}/history`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List members (grid) with filters and projections
     * 
     * @param {MembersServiceListMembersRequest} requestParameters Request parameters.
     */
    public listMembers(requestParameters: MembersServiceListMembersRequest, ): Observable<AxiosResponse<PagedMembersResponse>>;
    public listMembers(requestParameters: MembersServiceListMembersRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    q,
    status,
    categoryId,
    segmentId,
    communityId,
    nucleusId,
    from,
    to,
    view,
    include,
    expand,
    page,
    size,
    sort,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listMembers.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listMembers.');
        }

        let queryParameters = new URLSearchParams();
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (status !== undefined && status !== null) {
            queryParameters.append('status', <any>status);
        }
        if (categoryId !== undefined && categoryId !== null) {
            queryParameters.append('categoryId', <any>categoryId);
        }
        if (segmentId !== undefined && segmentId !== null) {
            queryParameters.append('segmentId', <any>segmentId);
        }
        if (communityId !== undefined && communityId !== null) {
            queryParameters.append('communityId', <any>communityId);
        }
        if (nucleusId !== undefined && nucleusId !== null) {
            queryParameters.append('nucleusId', <any>nucleusId);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (view !== undefined && view !== null) {
            queryParameters.append('view', <any>view);
        }
        if (include) {
            queryParameters['include'] = include.join(COLLECTION_FORMATS['csv']);
        }
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedMembersResponse>(`${this.basePath}/members`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
