/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CapabilitiesResponse } from '../model/capabilitiesResponse';
import { DashboardOverviewResponse } from '../model/dashboardOverviewResponse';
import { ErrorResponse } from '../model/errorResponse';
import { NavResponse } from '../model/navResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for getAdminDashboardOverview operation in NavigationService.
 * @export
 * @interface NavigationServiceGetAdminDashboardOverviewRequest
 */
export interface NavigationServiceGetAdminDashboardOverviewRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof NavigationServiceGetAdminDashboardOverview
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof NavigationServiceGetAdminDashboardOverview
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof NavigationServiceGetAdminDashboardOverview
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof NavigationServiceGetAdminDashboardOverview
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof NavigationServiceGetAdminDashboardOverview
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getCapabilities operation in NavigationService.
 * @export
 * @interface NavigationServiceGetCapabilitiesRequest
 */
export interface NavigationServiceGetCapabilitiesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly screen: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof NavigationServiceGetCapabilities
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getNav operation in NavigationService.
 * @export
 * @interface NavigationServiceGetNavRequest
 */
export interface NavigationServiceGetNavRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof NavigationServiceGetNav
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof NavigationServiceGetNav
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof NavigationServiceGetNav
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof NavigationServiceGetNav
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof NavigationServiceGetNav
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class NavigationService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Admin dashboard overview KPIs and operational counters
     * 
     * @param {NavigationServiceGetAdminDashboardOverviewRequest} requestParameters Request parameters.
     */
    public getAdminDashboardOverview(requestParameters: NavigationServiceGetAdminDashboardOverviewRequest, ): Observable<AxiosResponse<DashboardOverviewResponse>>;
    public getAdminDashboardOverview(requestParameters: NavigationServiceGetAdminDashboardOverviewRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getAdminDashboardOverview.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getAdminDashboardOverview.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<DashboardOverviewResponse>(`${this.basePath}/dashboard/overview`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get capabilities for a given screen (actions allowed)
     * 
     * @param {NavigationServiceGetCapabilitiesRequest} requestParameters Request parameters.
     */
    public getCapabilities(requestParameters: NavigationServiceGetCapabilitiesRequest, ): Observable<AxiosResponse<CapabilitiesResponse>>;
    public getCapabilities(requestParameters: NavigationServiceGetCapabilitiesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    screen,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getCapabilities.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getCapabilities.');
        }

        if (screen === null || screen === undefined) {
            throw new Error('Required parameter screen was null or undefined when calling getCapabilities.');
        }

        let queryParameters = new URLSearchParams();
        if (screen !== undefined && screen !== null) {
            queryParameters.append('screen', <any>screen);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<CapabilitiesResponse>(`${this.basePath}/capabilities`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get navigation model based on permissions, feature flags and context
     * 
     * @param {NavigationServiceGetNavRequest} requestParameters Request parameters.
     */
    public getNav(requestParameters: NavigationServiceGetNavRequest, ): Observable<AxiosResponse<NavResponse>>;
    public getNav(requestParameters: NavigationServiceGetNavRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getNav.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getNav.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<NavResponse>(`${this.basePath}/nav`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
