/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AsyncJobAcceptedResponse } from '../model/asyncJobAcceptedResponse';
import { CreatePointRuleRequest } from '../model/createPointRuleRequest';
import { ErrorResponse } from '../model/errorResponse';
import { PagedPointLedgerResponse } from '../model/pagedPointLedgerResponse';
import { PagedPointRulesResponse } from '../model/pagedPointRulesResponse';
import { PointPlanResponse } from '../model/pointPlanResponse';
import { PointPlansResponse } from '../model/pointPlansResponse';
import { PointRuleResponse } from '../model/pointRuleResponse';
import { PointsRecalculateRequest } from '../model/pointsRecalculateRequest';
import { UpdatePointPlanRequest } from '../model/updatePointPlanRequest';
import { UpdatePointRuleRequest } from '../model/updatePointRuleRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createPointRule operation in PointsService.
 * @export
 * @interface PointsServiceCreatePointRuleRequest
 */
export interface PointsServiceCreatePointRuleRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceCreatePointRule
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceCreatePointRule
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreatePointRuleRequest}
     * @memberof PointsServiceCreatePointRule
     */
    readonly createPointRuleRequest: CreatePointRuleRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceCreatePointRule
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceCreatePointRule
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceCreatePointRule
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getPointsLedger operation in PointsService.
 * @export
 * @interface PointsServiceGetPointsLedgerRequest
 */
export interface PointsServiceGetPointsLedgerRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly memberId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Start timestamp (inclusive)
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly from?: string

    /**
     * End timestamp (exclusive)
     * @type {string}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly to?: string

    /**
     * 
     * @type {number}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof PointsServiceGetPointsLedger
     */
    readonly size?: number
}

/**
 * Request parameters for listPointPlans operation in PointsService.
 * @export
 * @interface PointsServiceListPointPlansRequest
 */
export interface PointsServiceListPointPlansRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceListPointPlans
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceListPointPlans
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceListPointPlans
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceListPointPlans
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceListPointPlans
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listPointRules operation in PointsService.
 * @export
 * @interface PointsServiceListPointRulesRequest
 */
export interface PointsServiceListPointRulesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceListPointRules
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceListPointRules
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceListPointRules
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceListPointRules
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceListPointRules
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {boolean}
     * @memberof PointsServiceListPointRules
     */
    readonly active?: boolean

    /**
     * Free text search
     * @type {string}
     * @memberof PointsServiceListPointRules
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof PointsServiceListPointRules
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof PointsServiceListPointRules
     */
    readonly size?: number
}

/**
 * Request parameters for requestPointsRecalculation operation in PointsService.
 * @export
 * @interface PointsServiceRequestPointsRecalculationRequest
 */
export interface PointsServiceRequestPointsRecalculationRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly xOrgId: string

    /**
     * 
     * @type {PointsRecalculateRequest}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly pointsRecalculateRequest: PointsRecalculateRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceRequestPointsRecalculation
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for updatePointPlan operation in PointsService.
 * @export
 * @interface PointsServiceUpdatePointPlanRequest
 */
export interface PointsServiceUpdatePointPlanRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly planId: string

    /**
     * 
     * @type {UpdatePointPlanRequest}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly updatePointPlanRequest: UpdatePointPlanRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceUpdatePointPlan
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for updatePointRule operation in PointsService.
 * @export
 * @interface PointsServiceUpdatePointRuleRequest
 */
export interface PointsServiceUpdatePointRuleRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly ruleId: string

    /**
     * 
     * @type {UpdatePointRuleRequest}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly updatePointRuleRequest: UpdatePointRuleRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof PointsServiceUpdatePointRule
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class PointsService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create point rule
     * 
     * @param {PointsServiceCreatePointRuleRequest} requestParameters Request parameters.
     */
    public createPointRule(requestParameters: PointsServiceCreatePointRuleRequest, ): Observable<AxiosResponse<PointRuleResponse>>;
    public createPointRule(requestParameters: PointsServiceCreatePointRuleRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createPointRuleRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createPointRule.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createPointRule.');
        }

        if (createPointRuleRequest === null || createPointRuleRequest === undefined) {
            throw new Error('Required parameter createPointRuleRequest was null or undefined when calling createPointRule.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<PointRuleResponse>(`${this.basePath}/points/rules`,
                    createPointRuleRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Query points ledger entries (immutable)
     * 
     * @param {PointsServiceGetPointsLedgerRequest} requestParameters Request parameters.
     */
    public getPointsLedger(requestParameters: PointsServiceGetPointsLedgerRequest, ): Observable<AxiosResponse<PagedPointLedgerResponse>>;
    public getPointsLedger(requestParameters: PointsServiceGetPointsLedgerRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    memberId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    from,
    to,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getPointsLedger.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getPointsLedger.');
        }

        if (memberId === null || memberId === undefined) {
            throw new Error('Required parameter memberId was null or undefined when calling getPointsLedger.');
        }

        let queryParameters = new URLSearchParams();
        if (memberId !== undefined && memberId !== null) {
            queryParameters.append('memberId', <any>memberId);
        }
        if (from !== undefined && from !== null) {
            queryParameters.append('from', (<any>from).toISOString());
        }
        if (to !== undefined && to !== null) {
            queryParameters.append('to', (<any>to).toISOString());
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedPointLedgerResponse>(`${this.basePath}/points/ledger`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List point plans
     * 
     * @param {PointsServiceListPointPlansRequest} requestParameters Request parameters.
     */
    public listPointPlans(requestParameters: PointsServiceListPointPlansRequest, ): Observable<AxiosResponse<PointPlansResponse>>;
    public listPointPlans(requestParameters: PointsServiceListPointPlansRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listPointPlans.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listPointPlans.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PointPlansResponse>(`${this.basePath}/points/plans`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List point rules (admin)
     * 
     * @param {PointsServiceListPointRulesRequest} requestParameters Request parameters.
     */
    public listPointRules(requestParameters: PointsServiceListPointRulesRequest, ): Observable<AxiosResponse<PagedPointRulesResponse>>;
    public listPointRules(requestParameters: PointsServiceListPointRulesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    active,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listPointRules.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listPointRules.');
        }

        let queryParameters = new URLSearchParams();
        if (active !== undefined && active !== null) {
            queryParameters.append('active', <any>active);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedPointRulesResponse>(`${this.basePath}/points/rules`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Request points recalculation (async safe operation)
     * 
     * @param {PointsServiceRequestPointsRecalculationRequest} requestParameters Request parameters.
     */
    public requestPointsRecalculation(requestParameters: PointsServiceRequestPointsRecalculationRequest, ): Observable<AxiosResponse<AsyncJobAcceptedResponse>>;
    public requestPointsRecalculation(requestParameters: PointsServiceRequestPointsRecalculationRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    pointsRecalculateRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling requestPointsRecalculation.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling requestPointsRecalculation.');
        }

        if (pointsRecalculateRequest === null || pointsRecalculateRequest === undefined) {
            throw new Error('Required parameter pointsRecalculateRequest was null or undefined when calling requestPointsRecalculation.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AsyncJobAcceptedResponse>(`${this.basePath}/points/recalculate`,
                    pointsRecalculateRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update point plan
     * 
     * @param {PointsServiceUpdatePointPlanRequest} requestParameters Request parameters.
     */
    public updatePointPlan(requestParameters: PointsServiceUpdatePointPlanRequest, ): Observable<AxiosResponse<PointPlanResponse>>;
    public updatePointPlan(requestParameters: PointsServiceUpdatePointPlanRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    planId,
    updatePointPlanRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updatePointPlan.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updatePointPlan.');
        }

        if (planId === null || planId === undefined) {
            throw new Error('Required parameter planId was null or undefined when calling updatePointPlan.');
        }

        if (updatePointPlanRequest === null || updatePointPlanRequest === undefined) {
            throw new Error('Required parameter updatePointPlanRequest was null or undefined when calling updatePointPlan.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<PointPlanResponse>(`${this.basePath}/points/plans/${encodeURIComponent(String(planId))}`,
                    updatePointPlanRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update point rule
     * 
     * @param {PointsServiceUpdatePointRuleRequest} requestParameters Request parameters.
     */
    public updatePointRule(requestParameters: PointsServiceUpdatePointRuleRequest, ): Observable<AxiosResponse<PointRuleResponse>>;
    public updatePointRule(requestParameters: PointsServiceUpdatePointRuleRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    ruleId,
    updatePointRuleRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updatePointRule.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updatePointRule.');
        }

        if (ruleId === null || ruleId === undefined) {
            throw new Error('Required parameter ruleId was null or undefined when calling updatePointRule.');
        }

        if (updatePointRuleRequest === null || updatePointRuleRequest === undefined) {
            throw new Error('Required parameter updatePointRuleRequest was null or undefined when calling updatePointRule.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<PointRuleResponse>(`${this.basePath}/points/rules/${encodeURIComponent(String(ruleId))}`,
                    updatePointRuleRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
