/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ErrorResponse } from '../model/errorResponse';
import { MeResponse } from '../model/meResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for getMe operation in SessionService.
 * @export
 * @interface SessionServiceGetMeRequest
 */
export interface SessionServiceGetMeRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof SessionServiceGetMe
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof SessionServiceGetMe
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof SessionServiceGetMe
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof SessionServiceGetMe
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof SessionServiceGetMe
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class SessionService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Get current admin identity, scopes, roles and capabilities baseline
     * 
     * @param {SessionServiceGetMeRequest} requestParameters Request parameters.
     */
    public getMe(requestParameters: SessionServiceGetMeRequest, ): Observable<AxiosResponse<MeResponse>>;
    public getMe(requestParameters: SessionServiceGetMeRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getMe.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getMe.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MeResponse>(`${this.basePath}/me`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
