/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CommunityDetailResponse } from '../model/communityDetailResponse';
import { CreateStructureRequest } from '../model/createStructureRequest';
import { ErrorResponse } from '../model/errorResponse';
import { PagedCommunitiesResponse } from '../model/pagedCommunitiesResponse';
import { PagedNucleiResponse } from '../model/pagedNucleiResponse';
import { PagedStructuresResponse } from '../model/pagedStructuresResponse';
import { StructureDetailResponse } from '../model/structureDetailResponse';
import { StructureResponse } from '../model/structureResponse';
import { UpdateStructureRequest } from '../model/updateStructureRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createStructure operation in StructureService.
 * @export
 * @interface StructureServiceCreateStructureRequest
 */
export interface StructureServiceCreateStructureRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceCreateStructure
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceCreateStructure
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateStructureRequest}
     * @memberof StructureServiceCreateStructure
     */
    readonly createStructureRequest: CreateStructureRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceCreateStructure
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceCreateStructure
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceCreateStructure
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for getCommunity operation in StructureService.
 * @export
 * @interface StructureServiceGetCommunityRequest
 */
export interface StructureServiceGetCommunityRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceGetCommunity
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceGetCommunity
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof StructureServiceGetCommunity
     */
    readonly communityId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceGetCommunity
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceGetCommunity
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceGetCommunity
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof StructureServiceGetCommunity
     */
    readonly expand?: Array<string>
}

/**
 * Request parameters for getStructure operation in StructureService.
 * @export
 * @interface StructureServiceGetStructureRequest
 */
export interface StructureServiceGetStructureRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceGetStructure
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceGetStructure
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof StructureServiceGetStructure
     */
    readonly structureId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceGetStructure
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceGetStructure
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceGetStructure
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Expand nested resources, comma-separated
     * @type {Array<string>}
     * @memberof StructureServiceGetStructure
     */
    readonly expand?: Array<string>
}

/**
 * Request parameters for listCommunities operation in StructureService.
 * @export
 * @interface StructureServiceListCommunitiesRequest
 */
export interface StructureServiceListCommunitiesRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceListCommunities
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Free text search
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListCommunities
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListCommunities
     */
    readonly size?: number

    /**
     * Sort expression (e.g. createdAt:desc,name:asc)
     * @type {string}
     * @memberof StructureServiceListCommunities
     */
    readonly sort?: string
}

/**
 * Request parameters for listNuclei operation in StructureService.
 * @export
 * @interface StructureServiceListNucleiRequest
 */
export interface StructureServiceListNucleiRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceListNuclei
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly communityId?: string

    /**
     * Free text search
     * @type {string}
     * @memberof StructureServiceListNuclei
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListNuclei
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListNuclei
     */
    readonly size?: number
}

/**
 * Request parameters for listStructures operation in StructureService.
 * @export
 * @interface StructureServiceListStructuresRequest
 */
export interface StructureServiceListStructuresRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceListStructures
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * 
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly type?: string

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListStructures
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof StructureServiceListStructures
     */
    readonly size?: number

    /**
     * Sort expression (e.g. createdAt:desc,name:asc)
     * @type {string}
     * @memberof StructureServiceListStructures
     */
    readonly sort?: string
}

/**
 * Request parameters for updateStructure operation in StructureService.
 * @export
 * @interface StructureServiceUpdateStructureRequest
 */
export interface StructureServiceUpdateStructureRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof StructureServiceUpdateStructure
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof StructureServiceUpdateStructure
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof StructureServiceUpdateStructure
     */
    readonly structureId: string

    /**
     * 
     * @type {UpdateStructureRequest}
     * @memberof StructureServiceUpdateStructure
     */
    readonly updateStructureRequest: UpdateStructureRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof StructureServiceUpdateStructure
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof StructureServiceUpdateStructure
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof StructureServiceUpdateStructure
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class StructureService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create structure
     * 
     * @param {StructureServiceCreateStructureRequest} requestParameters Request parameters.
     */
    public createStructure(requestParameters: StructureServiceCreateStructureRequest, ): Observable<AxiosResponse<StructureResponse>>;
    public createStructure(requestParameters: StructureServiceCreateStructureRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createStructureRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createStructure.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createStructure.');
        }

        if (createStructureRequest === null || createStructureRequest === undefined) {
            throw new Error('Required parameter createStructureRequest was null or undefined when calling createStructure.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<StructureResponse>(`${this.basePath}/structures`,
                    createStructureRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get community detail
     * 
     * @param {StructureServiceGetCommunityRequest} requestParameters Request parameters.
     */
    public getCommunity(requestParameters: StructureServiceGetCommunityRequest, ): Observable<AxiosResponse<CommunityDetailResponse>>;
    public getCommunity(requestParameters: StructureServiceGetCommunityRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    communityId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    expand,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getCommunity.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getCommunity.');
        }

        if (communityId === null || communityId === undefined) {
            throw new Error('Required parameter communityId was null or undefined when calling getCommunity.');
        }

        let queryParameters = new URLSearchParams();
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<CommunityDetailResponse>(`${this.basePath}/communities/${encodeURIComponent(String(communityId))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Get structure detail
     * 
     * @param {StructureServiceGetStructureRequest} requestParameters Request parameters.
     */
    public getStructure(requestParameters: StructureServiceGetStructureRequest, ): Observable<AxiosResponse<StructureDetailResponse>>;
    public getStructure(requestParameters: StructureServiceGetStructureRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    structureId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    expand,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling getStructure.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getStructure.');
        }

        if (structureId === null || structureId === undefined) {
            throw new Error('Required parameter structureId was null or undefined when calling getStructure.');
        }

        let queryParameters = new URLSearchParams();
        if (expand) {
            queryParameters['expand'] = expand.join(COLLECTION_FORMATS['csv']);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<StructureDetailResponse>(`${this.basePath}/structures/${encodeURIComponent(String(structureId))}`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List communities
     * 
     * @param {StructureServiceListCommunitiesRequest} requestParameters Request parameters.
     */
    public listCommunities(requestParameters: StructureServiceListCommunitiesRequest, ): Observable<AxiosResponse<PagedCommunitiesResponse>>;
    public listCommunities(requestParameters: StructureServiceListCommunitiesRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    q,
    page,
    size,
    sort,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listCommunities.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listCommunities.');
        }

        let queryParameters = new URLSearchParams();
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedCommunitiesResponse>(`${this.basePath}/communities`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List nuclei by community (and optional filters)
     * 
     * @param {StructureServiceListNucleiRequest} requestParameters Request parameters.
     */
    public listNuclei(requestParameters: StructureServiceListNucleiRequest, ): Observable<AxiosResponse<PagedNucleiResponse>>;
    public listNuclei(requestParameters: StructureServiceListNucleiRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    communityId,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listNuclei.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listNuclei.');
        }

        let queryParameters = new URLSearchParams();
        if (communityId !== undefined && communityId !== null) {
            queryParameters.append('communityId', <any>communityId);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedNucleiResponse>(`${this.basePath}/nuclei`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List structures
     * 
     * @param {StructureServiceListStructuresRequest} requestParameters Request parameters.
     */
    public listStructures(requestParameters: StructureServiceListStructuresRequest, ): Observable<AxiosResponse<PagedStructuresResponse>>;
    public listStructures(requestParameters: StructureServiceListStructuresRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    type,
    page,
    size,
    sort,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listStructures.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listStructures.');
        }

        let queryParameters = new URLSearchParams();
        if (type !== undefined && type !== null) {
            queryParameters.append('type', <any>type);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters.append('sort', <any>sort);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedStructuresResponse>(`${this.basePath}/structures`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update structure
     * 
     * @param {StructureServiceUpdateStructureRequest} requestParameters Request parameters.
     */
    public updateStructure(requestParameters: StructureServiceUpdateStructureRequest, ): Observable<AxiosResponse<StructureResponse>>;
    public updateStructure(requestParameters: StructureServiceUpdateStructureRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    structureId,
    updateStructureRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updateStructure.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updateStructure.');
        }

        if (structureId === null || structureId === undefined) {
            throw new Error('Required parameter structureId was null or undefined when calling updateStructure.');
        }

        if (updateStructureRequest === null || updateStructureRequest === undefined) {
            throw new Error('Required parameter updateStructureRequest was null or undefined when calling updateStructure.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<StructureResponse>(`${this.basePath}/structures/${encodeURIComponent(String(structureId))}`,
                    updateStructureRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
