/**
 * Admin BFF API
 * Admin BFF (screen-first) API for Admin Platform. - Aggregates Core Domain Services for UI use-cases - Applies RBAC/ABAC and context enforcement (tenant/org/cycle) 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateSupplierRequest } from '../model/createSupplierRequest';
import { ErrorResponse } from '../model/errorResponse';
import { PagedSuppliersResponse } from '../model/pagedSuppliersResponse';
import { SupplierResponse } from '../model/supplierResponse';
import { UpdateSupplierRequest } from '../model/updateSupplierRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for createSupplier operation in SuppliersService.
 * @export
 * @interface SuppliersServiceCreateSupplierRequest
 */
export interface SuppliersServiceCreateSupplierRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly xOrgId: string

    /**
     * 
     * @type {CreateSupplierRequest}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly createSupplierRequest: CreateSupplierRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof SuppliersServiceCreateSupplier
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}

/**
 * Request parameters for listSuppliers operation in SuppliersService.
 * @export
 * @interface SuppliersServiceListSuppliersRequest
 */
export interface SuppliersServiceListSuppliersRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly xOrgId: string

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'

    /**
     * Free text search
     * @type {string}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly q?: string

    /**
     * 
     * @type {number}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof SuppliersServiceListSuppliers
     */
    readonly size?: number
}

/**
 * Request parameters for updateSupplier operation in SuppliersService.
 * @export
 * @interface SuppliersServiceUpdateSupplierRequest
 */
export interface SuppliersServiceUpdateSupplierRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly xTenantId: string

    /**
     * Organization identifier
     * @type {string}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly xOrgId: string

    /**
     * 
     * @type {string}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly supplierId: string

    /**
     * 
     * @type {UpdateSupplierRequest}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly updateSupplierRequest: UpdateSupplierRequest

    /**
     * Cycle identifier (required for cycle-scoped operations)
     * @type {string}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly xCycleId?: string

    /**
     * Client correlation id
     * @type {string}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly xRequestId?: string

    /**
     * Response language
     * @type {'pt-BR' | 'en' | 'es'}
     * @memberof SuppliersServiceUpdateSupplier
     */
    readonly acceptLanguage?: 'pt-BR' | 'en' | 'es'
}


@Injectable()
export class SuppliersService {

    protected basePath = 'https://api.example.com/admin-bff/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create supplier
     * 
     * @param {SuppliersServiceCreateSupplierRequest} requestParameters Request parameters.
     */
    public createSupplier(requestParameters: SuppliersServiceCreateSupplierRequest, ): Observable<AxiosResponse<SupplierResponse>>;
    public createSupplier(requestParameters: SuppliersServiceCreateSupplierRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    createSupplierRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling createSupplier.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling createSupplier.');
        }

        if (createSupplierRequest === null || createSupplierRequest === undefined) {
            throw new Error('Required parameter createSupplierRequest was null or undefined when calling createSupplier.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<SupplierResponse>(`${this.basePath}/suppliers`,
                    createSupplierRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * List suppliers
     * 
     * @param {SuppliersServiceListSuppliersRequest} requestParameters Request parameters.
     */
    public listSuppliers(requestParameters: SuppliersServiceListSuppliersRequest, ): Observable<AxiosResponse<PagedSuppliersResponse>>;
    public listSuppliers(requestParameters: SuppliersServiceListSuppliersRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    xCycleId,
    xRequestId,
    acceptLanguage,
    q,
    page,
    size,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling listSuppliers.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling listSuppliers.');
        }

        let queryParameters = new URLSearchParams();
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters.append('size', <any>size);
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<PagedSuppliersResponse>(`${this.basePath}/suppliers`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
    /**
     * Update supplier
     * 
     * @param {SuppliersServiceUpdateSupplierRequest} requestParameters Request parameters.
     */
    public updateSupplier(requestParameters: SuppliersServiceUpdateSupplierRequest, ): Observable<AxiosResponse<SupplierResponse>>;
    public updateSupplier(requestParameters: SuppliersServiceUpdateSupplierRequest, ): Observable<any> {
const {
    xTenantId,
    xOrgId,
    supplierId,
    updateSupplierRequest,
    xCycleId,
    xRequestId,
    acceptLanguage,
} = requestParameters;


        if (xTenantId === null || xTenantId === undefined) {
            throw new Error('Required parameter xTenantId was null or undefined when calling updateSupplier.');
        }

        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling updateSupplier.');
        }

        if (supplierId === null || supplierId === undefined) {
            throw new Error('Required parameter supplierId was null or undefined when calling updateSupplier.');
        }

        if (updateSupplierRequest === null || updateSupplierRequest === undefined) {
            throw new Error('Required parameter updateSupplierRequest was null or undefined when calling updateSupplier.');
        }

        let headers = {...this.defaultHeaders};
        if (xTenantId !== undefined && xTenantId !== null) {
            headers['X-Tenant-Id'] = String(xTenantId);
        }
        if (xOrgId !== undefined && xOrgId !== null) {
            headers['X-Org-Id'] = String(xOrgId);
        }
        if (xCycleId !== undefined && xCycleId !== null) {
            headers['X-Cycle-Id'] = String(xCycleId);
        }
        if (xRequestId !== undefined && xRequestId !== null) {
            headers['X-Request-Id'] = String(xRequestId);
        }
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers['Accept-Language'] = String(acceptLanguage);
        }

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<SupplierResponse>(`${this.basePath}/suppliers/${encodeURIComponent(String(supplierId))}`,
                    updateSupplierRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        headers: headers
                    }
                );
            })
        );
    }
}
